// Interface text for the interactive dashboards, written in digital-marketing language.
// Every key exists in both English and Arabic.

const en = {
  lang: "en" as "en" | "ar",
  f: { all: "All", week: "Latest week", month: "Last 4 weeks", allTime: "All time", channel: "AI channel", market: "Audience", product: "Product", segment: "Segment", clear: "Clear filters" },
  markets: { ar: "Arabic audience", en: "English audience" },
  marketsShort: { ar: "Arabic", en: "English" },
  products: { accounts: "Accounts", personal_finance: "Personal finance", home_finance: "Home finance", cards: "Cards", islamic: "Islamic banking", brand: "Brand searches" },
  personas: { government_employee: "Government employees", private_employee: "Private-sector employees", expat: "Expats", student: "Students", sme_owner: "SME owners", general: "General public" },
  kpi: {
    index: "AI Visibility Index",
    reach: "Brand reach",
    shortlist: "Shortlist rate",
    topMind: "Top-of-mind",
    sov: "Share of voice",
    sentiment: "Positive sentiment",
    alerts: "Misinformation alerts",
    rank: "Market rank",
  },
  help: {
    index: "A 0–100 score combining how often AI recommends Ahli Bank and how high in the answer it appears.",
    reach: "Share of AI answers that mention Ahli Bank at all.",
    shortlist: "Share of AI answers where Ahli Bank is among the first 3 banks recommended — the customer's shortlist.",
    topMind: "Share of AI answers where Ahli Bank is the first bank recommended.",
    sov: "Ahli Bank's share of all bank mentions across AI answers.",
    sentiment: "Of the answers that mention Ahli Bank, the share that talk about it positively.",
    alerts: "AI answers quoting rates or terms that differ from the Bank's approved figures.",
  },
  vsPrev: "vs previous period",
  of: "of",
  pts: "pts",
  answers: "AI answers",
  clickHint: "Click for details",
  nav: {
    insights: "Insights",
    act: "Take action",
    data: "Data",
    overview: "Overview",
    competitors: "Competitors",
    queries: "Customer queries",
    sources: "Media & sources",
    accuracy: "Brand accuracy",
    plan: "Growth plan",
    site: "Website readiness",
    ask: "Live AI test",
    responses: "Response feed",
    settings: "Settings",
    how: "How it works",
  },
  status: { demo: "Demo data", live: "Live tracking", hybrid: "Partly live", updated: "Updated" },
  overview: {
    title: "AI Visibility Overview",
    sub: "How often AI assistants recommend Ahli Bank when customers ask for banking advice in Oman.",
    trend: "Visibility trend",
    trendSub: "Pick a KPI above to change what's plotted",
    ahli: "Ahli Bank",
    leader: "Market leader",
    avg: "Market average",
    rank: "Ranking among Omani banks",
    rankSub: "Brand reach in AI answers",
    channels: "Performance by AI channel",
    channelsSub: "Brand reach on each assistant",
    markets: "Arabic vs English audience",
    marketsSub: "The same questions, asked in both languages",
    gap: "Language gap",
    products: "Product lines × AI channels",
    productsSub: "Brand reach per product and assistant. Darker = stronger.",
    sentiment: "Brand sentiment",
    sentimentSub: "Tone of answers that mention Ahli Bank",
    lost: "Who wins when we're missing",
    lostSub: "Banks AI recommends in answers that leave Ahli Bank out",
    media: "Media mix AI relies on",
    mediaSub: "Where the answers get their information",
    plan: "Growth plan",
    planSub: "Progress and forecast brand reach",
    openPlan: "Open growth plan",
    forecastTo: "Forecast in 12 weeks",
    done: "done",
    inProgress: "in progress",
    toDo: "to do",
    weak: "weak",
    strong: "strong",
    noData: "No tracking data yet. Run the first measurement from Settings.",
  },
  sent: { pos: "Positive", neu: "Neutral", neg: "Negative" },
  media: {
    own: "Owned (ahlibank.om)",
    competitor: "Competitor sites",
    lookalike: "Look-alike brands",
    comparison: "Comparison sites",
    news: "News & PR",
    community: "Forums & social",
    government: "Government",
    other: "Other",
  },
  drawer: {
    close: "Close",
    channel: "AI channel",
    market: "Audience",
    product: "Product line",
    segment: "Audience segment",
    week: "Week",
    bank: "Competitor profile",
    query: "Customer query",
    source: "Source",
    cell: "Product × channel",
    trend: "Weekly brand reach",
    byChannel: "By AI channel",
    byMarket: "By audience",
    byProduct: "By product line",
    competitors: "Banks recommended in these answers",
    sources: "Top sources cited",
    sample: "What the AI actually said",
    loading: "Loading answers…",
    viewAll: "Read all responses",
    focus: "Focus dashboard on this",
    vsAhli: "vs Ahli Bank",
    named: "Recommends Ahli Bank",
    notNamed: "Leaves Ahli Bank out",
    position: "position",
    simulated: "simulated",
    answersAnalysed: "answers analysed",
    ahliCited: "Answers citing ahlibank.om",
    citedIn: "Cited in",
    kindLabel: "Type",
    advice: "What to do",
    allAnswers: "All answers",
  },
  competitors: {
    title: "Competitive landscape",
    sub: "Every Omani bank, the same customer questions: who AI recommends, who it recommends first, and where Ahli Bank wins or loses.",
    position: "Ahli Bank's market rank",
    leader: "Market leader",
    gap: "Gap to leader",
    gapUnit: "pts of brand reach",
    map: "Positioning map",
    mapSub: "Brand reach (how often named) vs top-of-mind (how often named first). Bubble size = shortlist rate.",
    mapX: "Brand reach",
    mapY: "Top-of-mind",
    trend: "Brand reach over time",
    trendSub: "Click a bank to highlight it",
    board: "Leaderboard",
    boardSub: "Click a bank for its full profile",
    byChannel: "Brand reach by AI channel",
    byProduct: "Brand reach by product line",
    heatSub: "Click a cell to see the answers behind it",
    change: "Change",
    avgPos: "Avg. position",
    bank: "Bank",
  },
  queries: {
    title: "Customer queries",
    sub: "The questions customers really ask, and whether each AI channel recommends Ahli Bank. Click a cell to read the answer.",
    winRate: "Queries where Ahli is recommended",
    blind: "Blind spots",
    blindSub: "Queries where no AI channel recommends Ahli Bank",
    best: "Strongest queries",
    grid: "Query performance by channel",
    gridSub: "Share of answers recommending Ahli Bank. Click a cell for the answers.",
    manage: "Manage question library",
    query: "Query",
    intent: "Product",
    lang: "Language",
  },
  sources: {
    title: "Media & sources",
    sub: "The websites AI assistants read before they answer. Influence these sources and you influence the recommendation.",
    owned: "Owned-media citation rate",
    ownedSub: "AI answers that cite ahlibank.om",
    mix: "Media mix",
    mixSub: "Share of all citations, by type of source",
    top: "Most-cited websites",
    topSub: "Click a website to see where it shows up",
    pages: "Ahli Bank pages AI cites",
    noPages: "No ahlibank.om pages were cited in this period.",
    byChannel: "Owned-media citations by AI channel",
    advice: {
      comparison: "Keep Ahli Bank's rates and products current on this comparison site.",
      lookalike: "Brand confusion risk: strengthen 'Ahli Bank Oman' naming and Organization schema.",
      community: "Customers' own words: monitor and answer common questions publicly.",
      news: "Earned media: PR stories feed AI answers. Pitch product news here.",
      competitor: "A competitor's page is shaping the recommendation.",
      own: "Owned page AI trusts: keep it current and clear.",
      government: "Official source: make sure the Bank is listed correctly.",
      other: "Review whether Ahli Bank is represented here.",
    },
  },
  plan: {
    matrix: "Impact vs effort",
    matrixSub: "Top-left = quick wins. Click a bubble for the action.",
    impact: "Expected impact",
    effort: "Effort",
    low: "Low",
    high: "High",
    board: "Action board",
    progress: "Plan progress",
    forecast: "Brand reach forecast",
  },
};

export type UIText = typeof en;

const ar: UIText = {
  lang: "ar",
  f: { all: "الكل", week: "آخر أسبوع", month: "آخر 4 أسابيع", allTime: "كل الفترات", channel: "قناة الذكاء الاصطناعي", market: "الجمهور", product: "المنتج", segment: "الشريحة", clear: "مسح الفلاتر" },
  markets: { ar: "الجمهور العربي", en: "الجمهور الإنجليزي" },
  marketsShort: { ar: "عربي", en: "إنجليزي" },
  products: { accounts: "الحسابات", personal_finance: "التمويل الشخصي", home_finance: "التمويل السكني", cards: "البطاقات", islamic: "الصيرفة الإسلامية", brand: "البحث عن العلامة" },
  personas: { government_employee: "موظفو الحكومة", private_employee: "موظفو القطاع الخاص", expat: "المقيمون", student: "الطلاب", sme_owner: "أصحاب المشاريع", general: "الجمهور العام" },
  kpi: {
    index: "مؤشر الظهور في الذكاء الاصطناعي",
    reach: "وصول العلامة",
    shortlist: "معدل القائمة المختصرة",
    topMind: "الخيار الأول",
    sov: "حصة الصوت",
    sentiment: "الانطباع الإيجابي",
    alerts: "تنبيهات المعلومات الخاطئة",
    rank: "الترتيب في السوق",
  },
  help: {
    index: "مؤشر من 0 إلى 100 يجمع بين عدد مرات توصية الذكاء الاصطناعي بالبنك الأهلي وموقعه في الإجابة.",
    reach: "نسبة إجابات الذكاء الاصطناعي التي تذكر البنك الأهلي.",
    shortlist: "نسبة الإجابات التي يكون فيها البنك الأهلي ضمن أول 3 بنوك يوصى بها، أي القائمة المختصرة للعميل.",
    topMind: "نسبة الإجابات التي يكون فيها البنك الأهلي أول بنك يوصى به.",
    sov: "حصة البنك الأهلي من كل ذكر للبنوك في إجابات الذكاء الاصطناعي.",
    sentiment: "من الإجابات التي تذكر البنك الأهلي، نسبة التي تتحدث عنه بإيجابية.",
    alerts: "إجابات تذكر أسعاراً أو شروطاً تختلف عن الأرقام المعتمدة من البنك.",
  },
  vsPrev: "مقارنة بالفترة السابقة",
  of: "من",
  pts: "نقطة",
  answers: "إجابة",
  clickHint: "اضغط للتفاصيل",
  nav: {
    insights: "الرؤى",
    act: "التنفيذ",
    data: "البيانات",
    overview: "نظرة عامة",
    competitors: "المنافسون",
    queries: "استفسارات العملاء",
    sources: "الإعلام والمصادر",
    accuracy: "دقة رسائل العلامة",
    plan: "خطة النمو",
    site: "جاهزية الموقع",
    ask: "اختبار مباشر",
    responses: "سجل الإجابات",
    settings: "الإعدادات",
    how: "كيف يعمل النظام",
  },
  status: { demo: "بيانات تجريبية", live: "تتبع مباشر", hybrid: "مباشر جزئياً", updated: "آخر تحديث" },
  overview: {
    title: "نظرة عامة على الظهور في الذكاء الاصطناعي",
    sub: "كم مرة توصي مساعدات الذكاء الاصطناعي بالبنك الأهلي عندما يطلب العملاء نصيحة مصرفية في عُمان.",
    trend: "اتجاه الظهور",
    trendSub: "اختر مؤشراً من الأعلى لتغيير ما يُعرض",
    ahli: "البنك الأهلي",
    leader: "المتصدر",
    avg: "متوسط السوق",
    rank: "الترتيب بين البنوك العُمانية",
    rankSub: "وصول العلامة في إجابات الذكاء الاصطناعي",
    channels: "الأداء حسب قناة الذكاء الاصطناعي",
    channelsSub: "وصول العلامة في كل مساعد",
    markets: "الجمهور العربي مقابل الإنجليزي",
    marketsSub: "نفس الأسئلة بلغتين",
    gap: "الفجوة بين اللغتين",
    products: "المنتجات × قنوات الذكاء الاصطناعي",
    productsSub: "وصول العلامة لكل منتج ومساعد. الأغمق = أقوى.",
    sentiment: "انطباع العلامة",
    sentimentSub: "نبرة الإجابات التي تذكر البنك الأهلي",
    lost: "من يفوز عندما نغيب",
    lostSub: "البنوك التي يوصي بها الذكاء الاصطناعي في الإجابات التي لا تذكر البنك الأهلي",
    media: "المصادر التي يعتمد عليها الذكاء الاصطناعي",
    mediaSub: "من أين تأتي معلومات الإجابات",
    plan: "خطة النمو",
    planSub: "التقدّم والوصول المتوقع",
    openPlan: "افتح خطة النمو",
    forecastTo: "المتوقع خلال 12 أسبوعاً",
    done: "تم",
    inProgress: "قيد التنفيذ",
    toDo: "لم يبدأ",
    weak: "ضعيف",
    strong: "قوي",
    noData: "لا توجد بيانات بعد. شغّل أول قياس من الإعدادات.",
  },
  sent: { pos: "إيجابي", neu: "محايد", neg: "سلبي" },
  media: {
    own: "إعلام مملوك (ahlibank.om)",
    competitor: "مواقع المنافسين",
    lookalike: "علامات مشابهة الاسم",
    comparison: "مواقع المقارنة",
    news: "الأخبار والعلاقات العامة",
    community: "المنتديات والتواصل",
    government: "جهات حكومية",
    other: "أخرى",
  },
  drawer: {
    close: "إغلاق",
    channel: "قناة الذكاء الاصطناعي",
    market: "الجمهور",
    product: "المنتج",
    segment: "شريحة الجمهور",
    week: "الأسبوع",
    bank: "ملف المنافس",
    query: "استفسار العميل",
    source: "المصدر",
    cell: "منتج × قناة",
    trend: "وصول العلامة أسبوعياً",
    byChannel: "حسب قناة الذكاء الاصطناعي",
    byMarket: "حسب الجمهور",
    byProduct: "حسب المنتج",
    competitors: "البنوك الموصى بها في هذه الإجابات",
    sources: "أكثر المصادر استشهاداً",
    sample: "ماذا قال الذكاء الاصطناعي فعلاً",
    loading: "جارٍ تحميل الإجابات…",
    viewAll: "اقرأ كل الإجابات",
    focus: "ركّز اللوحة على هذا",
    vsAhli: "مقابل البنك الأهلي",
    named: "يوصي بالبنك الأهلي",
    notNamed: "لا يذكر البنك الأهلي",
    position: "الترتيب",
    simulated: "محاكاة",
    answersAnalysed: "إجابة تم تحليلها",
    ahliCited: "إجابات تستشهد بموقع ahlibank.om",
    citedIn: "مُستشهد به في",
    kindLabel: "النوع",
    advice: "ماذا نفعل",
    allAnswers: "كل الإجابات",
  },
  competitors: {
    title: "المشهد التنافسي",
    sub: "كل البنوك العُمانية ونفس أسئلة العملاء: من يوصي به الذكاء الاصطناعي، ومن يوصي به أولاً، وأين يتفوق البنك الأهلي أو يتأخر.",
    position: "ترتيب البنك الأهلي في السوق",
    leader: "المتصدر",
    gap: "الفارق عن المتصدر",
    gapUnit: "نقطة من وصول العلامة",
    map: "خريطة التموضع",
    mapSub: "وصول العلامة (كم مرة يُذكر) مقابل الخيار الأول (كم مرة يُذكر أولاً). حجم الدائرة = معدل القائمة المختصرة.",
    mapX: "وصول العلامة",
    mapY: "الخيار الأول",
    trend: "وصول العلامة عبر الوقت",
    trendSub: "اضغط على بنك لإبرازه",
    board: "لوحة الترتيب",
    boardSub: "اضغط على بنك لعرض ملفه الكامل",
    byChannel: "وصول العلامة حسب قناة الذكاء الاصطناعي",
    byProduct: "وصول العلامة حسب المنتج",
    heatSub: "اضغط على خانة لرؤية الإجابات خلفها",
    change: "التغير",
    avgPos: "متوسط الترتيب",
    bank: "البنك",
  },
  queries: {
    title: "استفسارات العملاء",
    sub: "الأسئلة التي يسألها العملاء فعلاً، وهل توصي كل قناة ذكاء اصطناعي بالبنك الأهلي. اضغط على خانة لقراءة الإجابة.",
    winRate: "استفسارات يُوصى فيها بالبنك الأهلي",
    blind: "نقاط عمياء",
    blindSub: "استفسارات لا توصي فيها أي قناة بالبنك الأهلي",
    best: "أقوى الاستفسارات",
    grid: "أداء الاستفسارات حسب القناة",
    gridSub: "نسبة الإجابات التي توصي بالبنك الأهلي. اضغط على خانة لقراءة الإجابات.",
    manage: "إدارة مكتبة الأسئلة",
    query: "الاستفسار",
    intent: "المنتج",
    lang: "اللغة",
  },
  sources: {
    title: "الإعلام والمصادر",
    sub: "المواقع التي يقرأها الذكاء الاصطناعي قبل أن يجيب. أثّر في هذه المصادر تؤثر في التوصية.",
    owned: "معدل الاستشهاد بالإعلام المملوك",
    ownedSub: "إجابات تستشهد بموقع ahlibank.om",
    mix: "مزيج المصادر",
    mixSub: "حصة كل نوع من مجموع الاستشهادات",
    top: "أكثر المواقع استشهاداً",
    topSub: "اضغط على موقع لترى أين يظهر",
    pages: "صفحات البنك الأهلي التي يستشهد بها الذكاء الاصطناعي",
    noPages: "لم تُستشهد أي صفحة من ahlibank.om في هذه الفترة.",
    byChannel: "الاستشهاد بالإعلام المملوك حسب القناة",
    advice: {
      comparison: "حدّث أسعار ومنتجات البنك الأهلي في موقع المقارنة هذا.",
      lookalike: "خطر الخلط بين العلامات: عزّز اسم «البنك الأهلي عُمان» والبيانات المنظمة.",
      community: "كلام العملاء أنفسهم: راقب وأجب عن الأسئلة الشائعة علناً.",
      news: "إعلام مكتسب: القصص الصحفية تغذي إجابات الذكاء الاصطناعي. أرسل أخبار المنتجات هنا.",
      competitor: "صفحة منافس تشكّل التوصية.",
      own: "صفحة مملوكة يثق بها الذكاء الاصطناعي: حافظ عليها محدّثة وواضحة.",
      government: "مصدر رسمي: تأكد أن البنك مدرج بشكل صحيح.",
      other: "راجع هل البنك الأهلي ممثّل في هذا الموقع.",
    },
  },
  plan: {
    matrix: "الأثر مقابل الجهد",
    matrixSub: "أعلى اليسار = مكاسب سريعة. اضغط على دائرة لعرض الإجراء.",
    impact: "الأثر المتوقع",
    effort: "الجهد",
    low: "منخفض",
    high: "مرتفع",
    board: "لوحة الإجراءات",
    progress: "تقدّم الخطة",
    forecast: "توقع وصول العلامة",
  },
};

export const UI: Record<"en" | "ar", UIText> = { en, ar };
