// Interface text for the dashboards: friendly and plain, with the marketing term kept as a small label.
// Every key exists in both English and Arabic. Placeholders like {n} are filled with `fill()`.

export const fill = (s: string, v: Record<string, string | number>) => s.replace(/\{(\w+)\}/g, (_, k) => String(v[k] ?? ""));

const en = {
  lang: "en" as "en" | "ar",
  f: { all: "All", week: "This week", month: "Last 4 weeks", allTime: "All time", channel: "AI assistant", market: "Language", product: "Product", segment: "Customer type", clear: "Reset" },
  markets: { ar: "Asking in Arabic", en: "Asking in English" },
  marketsShort: { ar: "Arabic", en: "English" },
  products: { accounts: "Accounts", personal_finance: "Personal finance", home_finance: "Home finance", cards: "Cards", islamic: "Islamic banking", brand: "About Ahli Bank" },
  personas: { government_employee: "Government employees", private_employee: "Private-sector employees", expat: "Expats", student: "Students", sme_owner: "Business owners", general: "Everyone" },
  kpi: {
    index: "Visibility score",
    reach: "We're mentioned",
    shortlist: "In the top 3",
    topMind: "Recommended first",
    sov: "Our share of the talk",
    sentiment: "Said nicely",
    alerts: "Wrong info about us",
    rank: "Our rank",
  },
  // the marketing term behind each friendly label
  term: { index: "AI Visibility Index", reach: "Brand reach", shortlist: "Shortlist rate", topMind: "Top-of-mind", sov: "Share of voice" },
  help: {
    index: "One number out of 100: how often AI recommends us, and how high up in the answer.",
    reach: "Out of all AI answers, how many mention Ahli Bank at all.",
    shortlist: "How often we're among the first 3 banks the AI suggests. Customers rarely look further.",
    topMind: "How often we're the very first bank the AI suggests.",
    sov: "Of all the bank names AI mentions, how much of that is us.",
    sentiment: "When AI talks about us, how often it's positive.",
    alerts: "Times AI quoted a rate or term that's different from our approved numbers.",
  },
  vsPrev: "vs before",
  of: "of",
  pts: "pts",
  answers: "answers",
  clickHint: "Tap for details",
  nav: {
    insights: "See",
    act: "Act",
    data: "More",
    overview: "Home",
    competitors: "Competitors",
    queries: "Customer questions",
    sources: "Where AI reads",
    accuracy: "Getting facts right",
    plan: "Growth plan",
    site: "Our website",
    ask: "Try it yourself",
    responses: "All answers",
    settings: "Settings",
    how: "How it works",
  },
  status: { demo: "Sample data", live: "Live", hybrid: "Partly live", updated: "Updated" },
  story: {
    s1: "Where are we today?",
    s2: "Who's ahead of us?",
    s3: "Where we win, where we lose",
    s4: "See it through the customer's eyes",
    s5: "Where does AI get its info?",
    s6: "What's next?",
    jump: "Jump to",
  },
  ins: {
    up: "Nice — we're up {d} points compared with before.",
    down: "Heads up — we're down {d} points compared with before.",
    flat: "About the same as before.",
    lead: "{bank} is ahead of us by {gap} points. Closing that gap is the goal.",
    weLead: "We're the most recommended bank. Let's keep it that way!",
    channels: "{best} recommends us the most ({bv}%), {worst} the least ({wv}%).",
    lang: "Customers asking in Arabic see us {gap} points less than in English.",
    langOk: "Arabic and English customers see us about the same.",
    products: "Strongest: {best} ({bv}%). Needs work: {worst} ({wv}%).",
    lost: "When AI leaves us out, it usually suggests {bank} instead.",
    sources: "AI reads {site} the most. Make sure our info there is up to date.",
    sov: "Out of every 10 bank mentions, about {n} are about us.",
    waffle: "Out of every 100 answers, {n} mention us",
  },
  overview: {
    title: "How does AI see us?",
    sub: "Every week we ask ChatGPT, Gemini and others the questions our customers ask — and check whether they recommend Ahli Bank.",
    trend: "How we're doing over time",
    trendSub: "Tap a number above to switch what you see here",
    ahli: "Ahli Bank",
    leader: "Top bank",
    avg: "Market average",
    rank: "Bank ranking",
    rankSub: "How often each bank is mentioned",
    race: "The bank race",
    channels: "Which AI likes us most?",
    channelsSub: "How often each assistant mentions us",
    markets: "Arabic or English?",
    marketsSub: "Same questions, two languages",
    gap: "Language gap",
    products: "Products × assistants",
    productsSub: "Darker = mentioned more. Tap any box.",
    sentiment: "How AI talks about us",
    sentimentSub: "Tone of the answers that mention us",
    lost: "Who takes our place?",
    lostSub: "Banks AI suggests when it doesn't mention us",
    missing: "of answers don't mention us",
    media: "Where AI gets its info",
    mediaSub: "The kinds of websites behind the answers",
    plan: "Our growth plan",
    planSub: "What's done, and where we could be in 12 weeks",
    openPlan: "Open the plan",
    forecastTo: "Where we could be in 12 weeks",
    done: "Done",
    inProgress: "In progress",
    toDo: "To do",
    weak: "Less",
    strong: "More",
    noData: "Nothing measured yet. Run the first check from Settings.",
    askLine: "A customer asks…",
    aiLine: "{ai} answers",
    nextQ: "Another question",
    typing: "typing…",
  },
  sent: { pos: "Positive", neu: "Neutral", neg: "Negative" },
  media: {
    own: "Our website",
    competitor: "Competitor websites",
    lookalike: "Similar-name banks",
    comparison: "Comparison sites",
    news: "News",
    community: "Forums & social",
    government: "Government",
    other: "Other",
  },
  drawer: {
    close: "Close",
    channel: "AI assistant",
    market: "Language",
    product: "Product",
    segment: "Customer type",
    week: "Week",
    bank: "Bank profile",
    query: "Customer question",
    source: "Website",
    cell: "Product × assistant",
    trend: "Week by week",
    byChannel: "By AI assistant",
    byMarket: "By language",
    byProduct: "By product",
    competitors: "Banks in these answers",
    sources: "Websites AI used",
    sample: "What the AI actually said",
    loading: "Loading answers…",
    viewAll: "Read all the answers",
    focus: "Show only this",
    vsAhli: "Compared with us",
    named: "Mentions us",
    notNamed: "Doesn't mention us",
    position: "position",
    simulated: "sample",
    answersAnalysed: "answers checked",
    ahliCited: "Answers that link to our website",
    citedIn: "Used in",
    kindLabel: "Type",
    advice: "What we can do",
    allAnswers: "All answers",
  },
  competitors: {
    title: "How do we compare?",
    sub: "Same customer questions, every Omani bank. Who gets recommended, who gets recommended first, and where we stand.",
    position: "Our rank",
    leader: "Top bank",
    gap: "Gap to the top",
    gapUnit: "points behind",
    map: "Who's where?",
    mapSub: "Right = mentioned more. Up = recommended first more often. Bigger circle = more often in the top 3.",
    mapX: "Mentioned more",
    mapY: "Recommended first more",
    trend: "Mentions over time",
    trendSub: "Tap a bank to highlight it",
    board: "The leaderboard",
    boardSub: "Tap any bank to see its full profile",
    byChannel: "Each bank on each AI assistant",
    byProduct: "Each bank by product",
    heatSub: "Tap a box to see the answers behind it",
    change: "Change",
    avgPos: "Avg. position",
    bank: "Bank",
  },
  queries: {
    title: "What customers ask",
    sub: "The real questions customers ask, and whether each AI assistant mentions us. Tap a box to read the answer.",
    winRate: "Questions where we show up",
    blind: "Where we're invisible",
    blindSub: "No AI assistant mentions us for these",
    best: "Our strongest questions",
    grid: "Every question, every assistant",
    gridSub: "How often we're mentioned. Tap a box to read the answers.",
    manage: "Edit the questions",
    query: "Question",
    intent: "Product",
    lang: "Language",
  },
  sources: {
    title: "Where AI reads",
    sub: "Before it answers, AI reads websites. Change what those websites say, and you change the answer.",
    owned: "Answers that link to us",
    ownedSub: "Answers that cite ahlibank.om",
    mix: "Kinds of websites",
    mixSub: "Share of all links, by type",
    top: "Websites AI reads most",
    topSub: "Tap a website to see where it shows up",
    pages: "Our pages AI uses",
    noPages: "None of our pages were used in this period.",
    byChannel: "Links to our website, by AI assistant",
    advice: {
      comparison: "Keep our rates and products up to date on this comparison site.",
      lookalike: "Risk of mix-up with a similar name: say 'Ahli Bank Oman' clearly on our pages.",
      community: "Real customer chatter: answer common questions here in public.",
      news: "News stories feed AI answers. Share product news here.",
      competitor: "A competitor's page is shaping the answer.",
      own: "AI trusts this page of ours: keep it fresh and clear.",
      government: "Official source: check we're listed correctly.",
      other: "Check whether Ahli Bank is mentioned here.",
    },
  },
  plan: {
    matrix: "Quick wins vs big projects",
    matrixSub: "Top-left = easy and high impact. Tap a circle to open the task.",
    impact: "Expected impact",
    effort: "Effort",
    low: "Low",
    high: "High",
    board: "Task board",
    progress: "Progress",
    forecast: "Where we could be",
  },
};

export type UIText = typeof en;

const ar: UIText = {
  lang: "ar",
  f: { all: "الكل", week: "هذا الأسبوع", month: "آخر 4 أسابيع", allTime: "كل الفترات", channel: "المساعد الذكي", market: "اللغة", product: "المنتج", segment: "نوع العميل", clear: "إعادة ضبط" },
  markets: { ar: "اللي يسألون بالعربي", en: "اللي يسألون بالإنجليزي" },
  marketsShort: { ar: "عربي", en: "إنجليزي" },
  products: { accounts: "الحسابات", personal_finance: "التمويل الشخصي", home_finance: "التمويل السكني", cards: "البطاقات", islamic: "الصيرفة الإسلامية", brand: "عن البنك الأهلي" },
  personas: { government_employee: "موظفو الحكومة", private_employee: "موظفو القطاع الخاص", expat: "المقيمون", student: "الطلاب", sme_owner: "أصحاب المشاريع", general: "الجميع" },
  kpi: {
    index: "مؤشر الظهور",
    reach: "نُذكر في",
    shortlist: "ضمن أول 3",
    topMind: "الخيار الأول",
    sov: "حصتنا من الحديث",
    sentiment: "كلام إيجابي",
    alerts: "معلومات غلط عنّا",
    rank: "ترتيبنا",
  },
  term: { index: "مؤشر الظهور في الذكاء الاصطناعي", reach: "وصول العلامة", shortlist: "معدل القائمة المختصرة", topMind: "أعلى الذهن", sov: "حصة الصوت" },
  help: {
    index: "رقم واحد من 100: كم مرة يرشّحنا الذكاء الاصطناعي، وفي أي مكان من الإجابة.",
    reach: "من كل إجابات الذكاء الاصطناعي، كم وحدة تذكر البنك الأهلي.",
    shortlist: "كم مرة نكون ضمن أول 3 بنوك يقترحها. العميل نادراً يشوف أبعد من كذا.",
    topMind: "كم مرة نكون أول بنك يقترحه الذكاء الاصطناعي.",
    sov: "من كل أسماء البنوك اللي يذكرها، كم نصيبنا منها.",
    sentiment: "لما يتكلم عنّا، كم مرة يكون كلامه إيجابي.",
    alerts: "مرات ذكر فيها الذكاء الاصطناعي سعر أو شرط يختلف عن أرقامنا المعتمدة.",
  },
  vsPrev: "مقارنة بقبل",
  of: "من",
  pts: "نقطة",
  answers: "إجابة",
  clickHint: "اضغط للتفاصيل",
  nav: {
    insights: "شوف",
    act: "اشتغل",
    data: "المزيد",
    overview: "الرئيسية",
    competitors: "المنافسون",
    queries: "أسئلة العملاء",
    sources: "من وين يقرأ؟",
    accuracy: "صحة المعلومات",
    plan: "خطة النمو",
    site: "موقعنا",
    ask: "جرّب بنفسك",
    responses: "كل الإجابات",
    settings: "الإعدادات",
    how: "كيف يشتغل؟",
  },
  status: { demo: "بيانات تجريبية", live: "مباشر", hybrid: "مباشر جزئياً", updated: "آخر تحديث" },
  story: {
    s1: "وين نحن اليوم؟",
    s2: "مين يسبقنا؟",
    s3: "وين نكسب ووين نخسر؟",
    s4: "شوف بعين العميل",
    s5: "من وين يجيب الذكاء الاصطناعي معلوماته؟",
    s6: "وش الخطوة الجاية؟",
    jump: "انتقل إلى",
  },
  ins: {
    up: "خبر حلو — ارتفعنا {d} نقطة مقارنة بقبل.",
    down: "انتبه — نزلنا {d} نقطة مقارنة بقبل.",
    flat: "تقريباً نفس المستوى السابق.",
    lead: "{bank} يسبقنا بـ {gap} نقطة. هدفنا نقرّب المسافة.",
    weLead: "نحن البنك الأكثر ترشيحاً. خلّنا نحافظ على الصدارة!",
    channels: "{best} أكثر واحد يذكرنا ({bv}%)، و{worst} الأقل ({wv}%).",
    lang: "العميل اللي يسأل بالعربي يشوفنا أقل بـ {gap} نقطة من الإنجليزي.",
    langOk: "العربي والإنجليزي يشوفوننا تقريباً بنفس الدرجة.",
    products: "أقوى منتج: {best} ({bv}%). يحتاج شغل: {worst} ({wv}%).",
    lost: "لما ما يذكرنا الذكاء الاصطناعي، غالباً يقترح {bank} بدالنا.",
    sources: "أكثر موقع يقرأه الذكاء الاصطناعي هو {site}. تأكد إن معلوماتنا فيه محدّثة.",
    sov: "من كل 10 مرات يُذكر فيها بنك، تقريباً {n} منها عنّا.",
    waffle: "من كل 100 إجابة، {n} تذكرنا",
  },
  overview: {
    title: "كيف يشوفنا الذكاء الاصطناعي؟",
    sub: "كل أسبوع نسأل ChatGPT وGemini وغيرهم نفس أسئلة عملائنا، ونشوف هل يرشّحون البنك الأهلي.",
    trend: "مستوانا مع الوقت",
    trendSub: "اضغط على أي رقم فوق عشان تغيّر اللي تشوفه هنا",
    ahli: "البنك الأهلي",
    leader: "البنك الأول",
    avg: "متوسط السوق",
    rank: "ترتيب البنوك",
    rankSub: "كم مرة يُذكر كل بنك",
    race: "سباق البنوك",
    channels: "أي مساعد يحبنا أكثر؟",
    channelsSub: "كم مرة يذكرنا كل مساعد",
    markets: "عربي ولا إنجليزي؟",
    marketsSub: "نفس الأسئلة بلغتين",
    gap: "الفرق بين اللغتين",
    products: "المنتجات × المساعدات",
    productsSub: "الأغمق = يذكرنا أكثر. اضغط على أي مربع.",
    sentiment: "كيف يتكلم عنّا؟",
    sentimentSub: "نبرة الإجابات اللي تذكرنا",
    lost: "مين ياخذ مكاننا؟",
    lostSub: "البنوك اللي يقترحها لما ما يذكرنا",
    missing: "من الإجابات ما تذكرنا",
    media: "من وين يجيب معلوماته؟",
    mediaSub: "أنواع المواقع اللي وراء الإجابات",
    plan: "خطة النمو",
    planSub: "وش خلّصنا، ووين ممكن نوصل خلال 12 أسبوع",
    openPlan: "افتح الخطة",
    forecastTo: "وين ممكن نوصل خلال 12 أسبوع",
    done: "تم",
    inProgress: "شغّالين عليه",
    toDo: "لم يبدأ",
    weak: "أقل",
    strong: "أكثر",
    noData: "ما فيه قياسات بعد. شغّل أول فحص من الإعدادات.",
    askLine: "عميل يسأل…",
    aiLine: "{ai} يرد",
    nextQ: "سؤال ثاني",
    typing: "يكتب…",
  },
  sent: { pos: "إيجابي", neu: "محايد", neg: "سلبي" },
  media: {
    own: "موقعنا",
    competitor: "مواقع المنافسين",
    lookalike: "بنوك بأسماء مشابهة",
    comparison: "مواقع المقارنة",
    news: "الأخبار",
    community: "المنتديات والتواصل",
    government: "جهات حكومية",
    other: "أخرى",
  },
  drawer: {
    close: "إغلاق",
    channel: "المساعد الذكي",
    market: "اللغة",
    product: "المنتج",
    segment: "نوع العميل",
    week: "الأسبوع",
    bank: "ملف البنك",
    query: "سؤال العميل",
    source: "الموقع",
    cell: "منتج × مساعد",
    trend: "أسبوع بأسبوع",
    byChannel: "حسب المساعد الذكي",
    byMarket: "حسب اللغة",
    byProduct: "حسب المنتج",
    competitors: "البنوك في هذه الإجابات",
    sources: "المواقع اللي استخدمها",
    sample: "وش قال الذكاء الاصطناعي بالضبط",
    loading: "جارٍ تحميل الإجابات…",
    viewAll: "اقرأ كل الإجابات",
    focus: "اعرض هذا فقط",
    vsAhli: "مقارنة فينا",
    named: "يذكرنا",
    notNamed: "ما يذكرنا",
    position: "الترتيب",
    simulated: "تجريبي",
    answersAnalysed: "إجابة تم فحصها",
    ahliCited: "إجابات فيها رابط لموقعنا",
    citedIn: "مستخدم في",
    kindLabel: "النوع",
    advice: "وش نقدر نسوي",
    allAnswers: "كل الإجابات",
  },
  competitors: {
    title: "كيف نقارن بالبنوك الثانية؟",
    sub: "نفس أسئلة العملاء لكل البنوك العُمانية: مين يُرشَّح، مين يُرشَّح أول، ووين موقعنا.",
    position: "ترتيبنا",
    leader: "البنك الأول",
    gap: "المسافة عن الأول",
    gapUnit: "نقطة ورا",
    map: "مين وين؟",
    mapSub: "يمين = يُذكر أكثر. فوق = يُرشَّح أول أكثر. الدائرة الأكبر = يكون ضمن أول 3 أكثر.",
    mapX: "يُذكر أكثر",
    mapY: "يُرشَّح أول أكثر",
    trend: "الذكر مع الوقت",
    trendSub: "اضغط على بنك عشان تبرزه",
    board: "لوحة الترتيب",
    boardSub: "اضغط على أي بنك لعرض ملفه كامل",
    byChannel: "كل بنك في كل مساعد",
    byProduct: "كل بنك حسب المنتج",
    heatSub: "اضغط على مربع لتشوف الإجابات وراه",
    change: "التغيّر",
    avgPos: "متوسط الترتيب",
    bank: "البنك",
  },
  queries: {
    title: "وش يسألون العملاء؟",
    sub: "الأسئلة اللي يسألها العملاء فعلاً، وهل كل مساعد يذكرنا فيها. اضغط على أي مربع لتقرأ الإجابة.",
    winRate: "أسئلة نظهر فيها",
    blind: "وين ما نظهر أبداً",
    blindSub: "ولا مساعد يذكرنا في هذه الأسئلة",
    best: "أقوى أسئلتنا",
    grid: "كل سؤال مع كل مساعد",
    gridSub: "كم مرة نُذكر. اضغط على مربع لتقرأ الإجابات.",
    manage: "تعديل الأسئلة",
    query: "السؤال",
    intent: "المنتج",
    lang: "اللغة",
  },
  sources: {
    title: "من وين يقرأ الذكاء الاصطناعي؟",
    sub: "قبل ما يجاوب، يقرأ مواقع. غيّر اللي تقوله هذه المواقع، تتغيّر الإجابة.",
    owned: "إجابات فيها رابط لنا",
    ownedSub: "إجابات تستشهد بموقع ahlibank.om",
    mix: "أنواع المواقع",
    mixSub: "نصيب كل نوع من كل الروابط",
    top: "أكثر المواقع قراءةً",
    topSub: "اضغط على موقع لتشوف وين يظهر",
    pages: "صفحاتنا اللي يستخدمها",
    noPages: "ما استُخدمت أي صفحة من موقعنا في هذه الفترة.",
    byChannel: "روابط لموقعنا حسب المساعد",
    advice: {
      comparison: "حدّث أسعارنا ومنتجاتنا في موقع المقارنة هذا.",
      lookalike: "فيه خطر خلط مع اسم مشابه: اكتب «البنك الأهلي عُمان» بوضوح في صفحاتنا.",
      community: "كلام العملاء الحقيقي: جاوب على الأسئلة الشائعة هنا علناً.",
      news: "الأخبار تغذي إجابات الذكاء الاصطناعي. شارك أخبار منتجاتنا هنا.",
      competitor: "صفحة منافس هي اللي تشكّل الإجابة.",
      own: "الذكاء الاصطناعي يثق بصفحتنا هذه: خلّها محدّثة وواضحة.",
      government: "مصدر رسمي: تأكد إننا مدرجين صح.",
      other: "شيك هل البنك الأهلي مذكور هنا.",
    },
  },
  plan: {
    matrix: "مكاسب سريعة ولا مشاريع كبيرة؟",
    matrixSub: "فوق على اليسار = سهل وأثره كبير. اضغط على دائرة لفتح المهمة.",
    impact: "الأثر المتوقع",
    effort: "الجهد",
    low: "قليل",
    high: "كبير",
    board: "لوحة المهام",
    progress: "التقدّم",
    forecast: "وين ممكن نوصل",
  },
};

export const UI: Record<"en" | "ar", UIText> = { en, ar };
